### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by jaollika** [JiiHu/Uolevi-Zombie-Shooter-6000#1]
Koodi on todella hyvää ja se sai minut harkitsemaan omaa harjoitustyötäni. 

Selvin erikoisuus on muuttujien ja luokkien englanninkielisyys ja että grafiikat on täysin ulkoistettu jollekin minulle tuntemattomalle luokalle. Gdx paketti tarjoaa todella paljon toiminnallisuutta jonka vuoksi osaa koodia on vaikea seurata. Osa kutsuista katoaa tähän mystiseen gdx pakettiin.

Jokainen luokka kuitenkin tekee vain yhtä asiaa ja metodit ovat lyhyitä ja helposti ymmärrettäviä.

Pelattavuudesta sen verran että 1.2. versiossa zombit ja pelaaja liikkuvat kulmittain noin 40% nopeammin, koska koodissa sallitaan liikkuminen X ja Y akselin suunnassa yhtäaikaa täydellä nopeudella.

**Comment by JiiHu** [comment]
Kiitos palautteesta!
