### ISSUE TITLE
Koodikatselmointi, repositorio @ 23.2.15 klo 18:54

### ISSUE THREAD

**Issue by ka-ke** [JiiHu/Uolevi-Zombie-Shooter-6000#2]
# Ohjelma
* Edellisessä katselmoinnissa havaittu bugi nopeuden muutoksesta liikkuessa kulmittain kummittelee yhä. Tämä näkyy selkeimmin, kun laittaa vastustajat kulkemaan suoraa linjaa.
* Vastukset pakkaantuvat aika nopeasti yhteen nippuun, jolloin väistely muuttuu todella helpoksi.
* Liikkuessaan alareunassa, pelaaja ei ylitä kentän reunoja yhtä paljoa kuin muilla sivuilla.
* Sulkiessa ohjelman ruksista tulostuu virheviesti.
* Käynnistäessä ja ohjelman pyörimisen aikana oli koko ajan jotakin paketti latauksia taustalla.
* Hahmojen tekstuurit ovat selkeät ja värien vaihtelu tuo eloa vastustajiin. Toivottavasti kenttäkin kerkeää saada tunnelmallisempaa väritystä.
* Odotan innolla, kuinka ampuminen tulee toimimaan!

# Koodi
* Ohjelma on jaoteltu siististi domain, logiikka, UI ja game paketteihin.
* Dependencies osioista löytyy huikeasti ylemmän tason koodia, jota on ilmeisesti käytetty tarpeeseen.
* Single Responsibility pätee hyvin lähes kaikissa luokissa ja metodeissa. Jälkimmäiset ovat myös riittävän kompakteja huolimatta reaaliaikaisen pelin monimutkaisesta logiikasta.
* Erityisen mukavaa oli eri ohjaajien paljous työnjako logiikassa.
* Nimeäminen on selkeää, etenkin jos lukijalla on kokemusta peliohjelmoinnista.
* UI:n piirtotyön hoitavalla luokalla on paljon tehtävää eikä javadocia vielä työstetty, joidenkin metodien tehtävä ei täysin vielä avautunut.

# Testit
* Testejä on kaikissa paketeissa, erityisen paljon domainissa.
* Jotkut logiikan testit eivät tunnu kovin kattavilta:

    @Test
    public void mousePositionWorks() {
        int angle = player.getAngle();
        ic.mousePosition(100, 100);
        assertTrue(angle != player.getAngle());

# Dokumentointi
* Luokkakaaviot ovat kattavia ja näyttävät kivasti ohjelman kartoittamisprosessin.
* Skevenssikaaviot ovat huolellisesti tehdyt.
* Hyvässä tahdissa olet saanut aikaan monipuolisen peliprojektin.

**Comment by JiiHu** [comment]
Kiitoksia hyvin tehdystä ja tarkasta palautteeesta! Alla kommentteja selventämään kurssin ohjaajille ja sinulle tekemiäni päätöksiä: 

#### Ampuminen
- Ampuminen itseasiassa toimii jo, mutta se on toteutettu hieman tylsästi: kun pelaaja klikkaa Zombien päällä hiirellä, ampuu pelaaja silloin Zombieta

#### Vastuksien pakkaantuminen
- Tuo on totta alemmilla tasoilla, mutta onneksi peli alkaa käydä todella hankalaksi kun pelaa muutaman Levelin eteenpäin ja Zombeja tulee joka suunnasta sen verran, että niitä on vaikea väistellä pakkaantumisesta huolimatta. Kokeilin tämän korjaamista aikaisemmin, mutta se aiheutti erinäisiä ongelmia, joten jätin pakkaantumisen pelin ominaisuudeksi.

#### Bugi kulmittain liikkumisesta
- Bugihan johtuu siitä että kulmittain ollessa Zombie liikkuu kahteen suuntaan yhden sijaan. Koska kaikkien hahmojen liikkuminen on toteutettu pikselikartassa, en keksi mitään tapaa jolla voisi liikkua esimerkiksi vain 0.7 pikseliä nurkkaan päin. Koska pelaaja voi kuitenkin liikkua itsekin nopeammin menemällä kulmittain, en koe että tämä olisi kovinkaan suuri ongelma. Asian voisi toki korjata niin että hahmot voivat liikkua vain yhteen suuntaan kerrallaan ja sanoa että se on ominaisuus, mutta minusta tekemäni tapa on kuitenkin pelattavuuden kannalta parempi tapa.

#### Testit
- Olet oikeassa, jotkin testit voisivat olla kattavampia. On kuitenkin vaikea konstruoida kaikkia mahdollisia tilanteita ja esimerkiksi juuri tarkastelemassasi esimerkissä laskea missä kulmassa Playerin pitäisi olla suhteessa hiireen, joten varmistan vain että se toimii jossain määrin. Jos taas jokin koodimuutos rikkoisi pelaajan kääntymisen kokonaan, sen huomaisi heti pelatessa.

**Comment by ka-ke** [comment]
Hyvä kun mainitsit, että ampuminen toimii jo. Kokeilin peliä uudestaan ja mainitsen nyt vielä yhdestä havaitsemastani erikoisominaisuudesta: jonossa sinua kohti tulevia vastuksia voi ampua lopusta alkuu, ts. luodit menevät kaiken läpi ja peli toimii ikään kuin point and clicker räiskintä.
